// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Vending_Machine_App.Models;

#nullable disable

namespace Vending_Machine_App.Migrations
{
    [DbContext(typeof(VendingMachineDbContext))]
    [Migration("20250211124921_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Vending_Machine_App.Models.Item", b =>
                {
                    b.Property<int>("ItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("item_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ItemId"));

                    b.Property<string>("Category")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ItemName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("item_name");

                    b.Property<decimal?>("ItemPrice")
                        .HasColumnType("decimal(10, 2)")
                        .HasColumnName("item_price");

                    b.Property<int?>("ItemQuantity")
                        .HasColumnType("int")
                        .HasColumnName("item_quantity");

                    b.HasKey("ItemId")
                        .HasName("PK__items__52020FDD8B472EAF");

                    b.ToTable("items", (string)null);

                    b.HasData(
                        new
                        {
                            ItemId = 1,
                            Category = "Drink",
                            ItemName = "Sprite",
                            ItemPrice = 20.00m,
                            ItemQuantity = 10
                        },
                        new
                        {
                            ItemId = 2,
                            Category = "Drink",
                            ItemName = "Coke",
                            ItemPrice = 5.00m,
                            ItemQuantity = 10
                        },
                        new
                        {
                            ItemId = 3,
                            Category = "Drink",
                            ItemName = "Water",
                            ItemPrice = 20.00m,
                            ItemQuantity = 10
                        },
                        new
                        {
                            ItemId = 4,
                            Category = "Snack",
                            ItemName = "Oreo",
                            ItemPrice = 5.00m,
                            ItemQuantity = 1
                        },
                        new
                        {
                            ItemId = 5,
                            Category = "Snack",
                            ItemName = "Chips",
                            ItemPrice = 20.00m,
                            ItemQuantity = 10
                        },
                        new
                        {
                            ItemId = 7,
                            Category = "Drink",
                            ItemName = "Pepsi",
                            ItemPrice = 10.00m,
                            ItemQuantity = 10
                        },
                        new
                        {
                            ItemId = 6,
                            Category = "Drink",
                            ItemName = "Twist",
                            ItemPrice = 20.00m,
                            ItemQuantity = 10
                        },
                        new
                        {
                            ItemId = 8,
                            Category = "Drink",
                            ItemName = "Stoney",
                            ItemPrice = 10.00m,
                            ItemQuantity = 10
                        },
                        new
                        {
                            ItemId = 9,
                            Category = "Snack",
                            ItemName = "BarOne",
                            ItemPrice = 5.00m,
                            ItemQuantity = 10
                        });
                });

            modelBuilder.Entity("Vending_Machine_App.Models.Purchase", b =>
                {
                    b.Property<int>("PurchaseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("purchase_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PurchaseId"));

                    b.Property<decimal>("AmountPaid")
                        .HasColumnType("decimal(10, 2)")
                        .HasColumnName("amount_paid");

                    b.Property<decimal?>("Change")
                        .HasColumnType("decimal(10, 2)")
                        .HasColumnName("change");

                    b.Property<int>("ItemId")
                        .HasColumnType("int")
                        .HasColumnName("item_id");

                    b.Property<string>("ItemName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("item_name");

                    b.Property<DateTime>("PurchaseDate")
                        .HasColumnType("datetime")
                        .HasColumnName("purchase_date");

                    b.HasKey("PurchaseId")
                        .HasName("PK__purchase__87071CB95534AE18");

                    b.HasIndex("ItemId");

                    b.ToTable("purchases", (string)null);
                });

            modelBuilder.Entity("Vending_Machine_App.Models.Purchase", b =>
                {
                    b.HasOne("Vending_Machine_App.Models.Item", "Item")
                        .WithMany()
                        .HasForeignKey("ItemId")
                        .IsRequired()
                        .HasConstraintName("FK_purchases_items");

                    b.Navigation("Item");
                });
#pragma warning restore 612, 618
        }
    }
}
