services:
  - type: web
    name: vending-machine-app
    env: docker
    dockerfilePath: Dockerfile  # If you have a Dockerfile, keep this line
    startCommand: dotnet Vending-Machine-App.dll
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
    ports:
      - 8080